version: '2'
services:
    jflow-app:
        image: jflow
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jflow-postgresql:5432/jflow
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jflow-postgresql:
        extends:
            file: postgresql.yml
            service: jflow-postgresql
